---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: ws
  spec:
    containers:
    - name: dev
      image: eclipse/che-theia-dev:nightly
      resources:
        limits:
          memory: 2048Mi
      volumeMounts:
      - mountPath: /projects
        name: projects
    - name: dev-plugin
      image: eclipse/che-theia-dev:nightly
      resources:
        limits:
          memory: 2048Mi
      volumeMounts:
      - mountPath: /projects
        name: projects
    volumes:
    - name: projects
      persistentVolumeClaim:
        claimName: projects
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: projects
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
